version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studio360-backend
    env_file:
      - ./backend/.env.docker
    ports:
      - '3001:3001'
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/python/poppler:/usr/src/app/python/poppler
    depends_on:
      - n8n
    networks:
      - studio360

  n8n:
    image: n8nio/n8n:latest
    container_name: studio360-n8n
    ports:
      - '5678:5678'
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=UTC
      # Optional encryption key for credentials (set for production)
      #- N8N_ENCRYPTION_KEY=change-me
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - studio360

networks:
  studio360:
    driver: bridge

volumes:
  n8n_data:
    driver: local
