version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studio360-backend
    env_file:
      - ./backend/.env.docker
    ports:
      - '3001:3001'
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/python/poppler:/usr/src/app/python/poppler
    networks:
      - studio360

networks:
  studio360:
    driver: bridge
